import * as Y from 'yjs'
import type { Entity, Relationship, Field, FieldType } from './board'

// ---- shared ----
export function ident(name: string): string {
  const slug = name.trim().toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/^_+|_+$/g, '')
  return slug || 'unnamed'
}
function pkField(e: Entity): Field | undefined {
  return e.fields.find(f => f.type === 'pk') ?? e.fields.find(f => f.name.trim().toLowerCase() === 'id')
}
interface Resolved { fromCol: string; toCol: string; synthesized: boolean }
function resolveCols(r: Relationship, from: Entity, to: Entity): Resolved {
  let synthesized = false
  const fromF = r.fromField ? from.fields.find(f => f.id === r.fromField) : undefined
  const toF = r.toField ? to.fields.find(f => f.id === r.toField) : undefined
  let fromCol = fromF?.name
  let toCol = toF?.name ?? pkField(to)?.name
  if (!fromCol) {
    const fk = from.fields.find(f => f.type === 'fk' && ident(f.name).includes(ident(to.name)))
      ?? from.fields.find(f => f.type === 'fk')
    fromCol = fk?.name ?? `${ident(to.name)}_id`
    synthesized = true
  }
  if (!toCol) { toCol = 'id'; synthesized = true }
  return { fromCol: ident(fromCol), toCol: ident(toCol), synthesized }
}

// ---- DBML (column-level refs with cardinality + role) ----
const DBML_TYPE: Record<FieldType, string> = {
  pk: 'int', fk: 'int', string: 'varchar', text: 'text', number: 'numeric',
  boolean: 'boolean', date: 'date', timestamp: 'timestamp', email: 'varchar',
}
function dbmlOp(r: Relationship): string {
  if (r.fromCard === 'one' && r.toCard === 'many') return '<'
  if (r.fromCard === 'many' && r.toCard === 'one') return '>'
  if (r.fromCard === 'many' && r.toCard === 'many') return '<>'
  return '-'
}
export function toDBML(entities: Entity[], rels: Relationship[]): string {
  const byId = new Map(entities.map(e => [e.id, e]))
  const lines: string[] = ['// Generated by JotModel', '']
  for (const e of entities) {
    lines.push(`Table ${ident(e.name)} {`)
    if (e.fields.length === 0) lines.push('  // (no fields yet)')
    for (const f of e.fields) {
      const suffix = f.type === 'pk' ? ' [pk]' : ''
      lines.push(`  ${ident(f.name)} ${DBML_TYPE[f.type]}${suffix}`)
    }
    lines.push('}', '')
  }
  if (rels.length) {
    lines.push('// Relationships')
    for (const r of rels) {
      const from = byId.get(r.fromId), to = byId.get(r.toId)
      if (!from || !to) continue
      const { fromCol, toCol, synthesized } = resolveCols(r, from, to)
      const name = r.role ? `${ident(r.role)}: ` : ''
      const note = synthesized ? '  // synthesized — bind a field to make this an exact FK' : ''
      lines.push(`Ref ${name}${ident(from.name)}.${fromCol} ${dbmlOp(r)} ${ident(to.name)}.${toCol}${note}`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

// ---- dbt (schema.yml + model stubs) ----
export function toDbt(entities: Entity[], rels: Relationship[]): string {
  const byId = new Map(entities.map(e => [e.id, e]))
  const relsBySource = new Map<string, Relationship[]>()
  for (const r of rels) (relsBySource.get(r.fromId) ?? relsBySource.set(r.fromId, []).get(r.fromId)!).push(r)

  const yml: string[] = ['version: 2', '', 'models:']
  for (const e of entities) {
    yml.push(`  - name: ${ident(e.name)}`)
    if (e.fields.length) {
      yml.push('    columns:')
      for (const f of e.fields) {
        yml.push(`      - name: ${ident(f.name)}`)
        const tests: string[] = []
        if (f.type === 'pk') tests.push('unique', 'not_null')
        // relationships test for fk fields we can resolve
        const rel = (relsBySource.get(e.id) ?? []).find(r => r.fromField === f.id)
        if (rel) {
          const to = byId.get(rel.toId)
          if (to) {
            const toCol = (to.fields.find(x => x.id === rel.toField)?.name) ?? pkField(to)?.name ?? 'id'
            yml.push('        tests:')
            tests.forEach(t => yml.push(`          - ${t}`))
            yml.push('          - relationships:')
            yml.push(`              to: ref('${ident(to.name)}')`)
            yml.push(`              field: ${ident(toCol)}`)
            continue
          }
        }
        if (tests.length) { yml.push('        tests:'); tests.forEach(t => yml.push(`          - ${t}`)) }
      }
    }
  }

  const out: string[] = ['# ===== file: models/schema.yml =====', yml.join('\n'), '']
  for (const e of entities) {
    const cols = e.fields.length ? e.fields.map(f => `  ${ident(f.name)}`).join(',\n') : '  -- (no fields yet)'
    out.push(`# ===== file: models/${ident(e.name)}.sql =====`)
    out.push(`-- {{ config(materialized='view') }}`)
    out.push(`select\n${cols}\nfrom {{ source('raw', '${ident(e.name)}') }}`)
    out.push('')
  }
  return out.join('\n')
}

// ---- SQL DDL (per dialect) ----
export type Dialect = 'postgres' | 'mysql' | 'sqlserver'
const SQL_TYPE: Record<Dialect, Record<FieldType, string>> = {
  postgres: { pk: 'serial', fk: 'integer', string: 'varchar(255)', text: 'text', number: 'numeric', boolean: 'boolean', date: 'date', timestamp: 'timestamptz', email: 'varchar(320)' },
  mysql: { pk: 'int auto_increment', fk: 'int', string: 'varchar(255)', text: 'text', number: 'decimal(12,2)', boolean: 'tinyint(1)', date: 'date', timestamp: 'datetime', email: 'varchar(320)' },
  sqlserver: { pk: 'int identity(1,1)', fk: 'int', string: 'nvarchar(255)', text: 'nvarchar(max)', number: 'decimal(12,2)', boolean: 'bit', date: 'date', timestamp: 'datetime2', email: 'nvarchar(320)' },
}
function q(dialect: Dialect, name: string): string {
  const id = ident(name)
  return dialect === 'mysql' ? `\`${id}\`` : dialect === 'sqlserver' ? `[${id}]` : `"${id}"`
}
export function toSQL(entities: Entity[], rels: Relationship[], dialect: Dialect): string {
  const byId = new Map(entities.map(e => [e.id, e]))
  const types = SQL_TYPE[dialect]
  const out: string[] = [`-- Generated by JotModel · ${dialect} DDL`, '']
  for (const e of entities) {
    const cols: string[] = []
    for (const f of e.fields) {
      const pk = f.type === 'pk' ? ' primary key' : ''
      cols.push(`  ${q(dialect, f.name)} ${types[f.type]}${pk}`)
    }
    if (cols.length === 0) cols.push('  -- (no fields yet)')
    out.push(`create table ${q(dialect, e.name)} (`)
    out.push(cols.join(',\n'))
    out.push(');', '')
  }
  const fks: string[] = []
  for (const r of rels) {
    const from = byId.get(r.fromId), to = byId.get(r.toId)
    if (!from || !to || r.fromId === r.toId) continue
    const { fromCol, toCol } = resolveCols(r, from, to)
    const cname = ident(`fk_${from.name}_${r.role || to.name}`)
    fks.push(`alter table ${q(dialect, from.name)} add constraint ${q(dialect, cname)} ` +
      `foreign key (${q(dialect, fromCol)}) references ${q(dialect, to.name)} (${q(dialect, toCol)});`)
  }
  if (fks.length) { out.push('-- Foreign keys'); out.push(...fks); out.push('') }
  return out.join('\n')
}

// ---- .jotmodel (portable CRDT update in a JSON envelope) ----
const CHUNK = 0x8000
function toBase64(bytes: Uint8Array): string {
  let s = ''
  for (let i = 0; i < bytes.length; i += CHUNK) s += String.fromCharCode(...bytes.subarray(i, i + CHUNK))
  return btoa(s)
}
function fromBase64(b64: string): Uint8Array {
  const s = atob(b64); const out = new Uint8Array(s.length)
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i)
  return out
}
export interface JotmodelEnvelope { format: 'jotmodel'; version: number; schema: number; title: string; exportedAt: string; update: string }
export function exportJotmodel(doc: Y.Doc, title = 'untitled board'): string {
  const env: JotmodelEnvelope = {
    format: 'jotmodel', version: 1, schema: 2, title,
    exportedAt: new Date().toISOString(),
    update: toBase64(Y.encodeStateAsUpdate(doc)),
  }
  return JSON.stringify(env, null, 2)
}
export function parseJotmodel(text: string): { update: Uint8Array; meta: JotmodelEnvelope } {
  const env = JSON.parse(text) as JotmodelEnvelope
  if (env.format !== 'jotmodel') throw new Error('Not a .jotmodel file')
  return { update: fromBase64(env.update), meta: env }
}

// ---- download ----
export function download(filename: string, text: string) {
  const blob = new Blob([text], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
